"""Specs for the CP8 IaC generator (`disk_tree.iac`) and its CLI."""
from __future__ import annotations

from click.testing import CliRunner

from disk_tree.cli import cli
from disk_tree.cli.sync import BucketCfg, SyncCfg
from disk_tree.iac import aws_batch_tfvars, binding_name, dashboard_config, r2_bindings_toml, r2_hosts, s3_hosts


def _cfg(uris, delete=None) -> SyncCfg:
    return SyncCfg(listings="x", buckets=[BucketCfg(uri=u) for u in uris], delete=delete)


def test_binding_name_sanitizes_to_identifier():
    assert (binding_name("nj-crashes"), binding_name("ctbk")) == ("R2_nj_crashes", "R2_ctbk")


def test_r2_hosts_are_r2_only_deduped_in_order():
    assert r2_hosts(_cfg(["r2://ctbk", "s3://sb", "r2://nj-crashes", "r2://ctbk"])) == ["ctbk", "nj-crashes"]


def test_r2_bindings_toml_binds_each_r2_bucket():
    assert r2_bindings_toml(_cfg(["r2://ctbk", "r2://nj-crashes"])).split("\n") == [
        "# Generated by `disk-tree iac r2-bindings` — R2 CFN executor bindings",
        "# (spec `specs/staged-delete.md` CP7). Paste into ui/wrangler.toml, redeploy.",
        "",
        "[[r2_buckets]]",
        'binding = "R2_ctbk"',
        'bucket_name = "ctbk"',
        "",
        "[[r2_buckets]]",
        'binding = "R2_nj_crashes"',
        'bucket_name = "nj-crashes"',
        "",
    ]


def test_r2_bindings_toml_empty_when_no_r2():
    assert r2_bindings_toml(_cfg(["s3://sb"])) == "# no r2:// buckets in buckets.yml — nothing to bind for the R2 CFN\n"


def test_dashboard_config_shapes_the_component_input():
    cfg = _cfg(["r2://ctbk", "s3://sb"], delete={"approval": "user-choice", "chat": "discord", "threshold": 500})
    assert dashboard_config(cfg, project="dt-demo") == {
        "project": "dt-demo",
        "dataBucket": "disk-tree",
        "deleteThreshold": 500,
        "deleteApproval": "user-choice",
        "chat": "discord",
        "executorBuckets": [{"binding": "R2_ctbk", "bucket": "ctbk"}],
    }


def test_dashboard_config_defaults_when_no_delete_block():
    cfg = _cfg(["r2://ctbk"])
    assert dashboard_config(cfg) == {
        "project": "disk-tree",
        "dataBucket": "disk-tree",
        "deleteThreshold": 1000,
        "deleteApproval": "staged",
        "chat": "none",
        "executorBuckets": [{"binding": "R2_ctbk", "bucket": "ctbk"}],
    }


def test_s3_hosts_are_s3_only_deduped_in_order():
    assert s3_hosts(_cfg(["s3://alpha", "r2://ctbk", "s3://beta", "s3://alpha"])) == ["alpha", "beta"]


def test_aws_batch_tfvars():
    assert aws_batch_tfvars(_cfg(["s3://alpha", "r2://ctbk", "s3://beta"]), region="us-west-2", project="dt").split("\n") == [
        "# Generated by `disk-tree iac aws-batch` — AWS Batch delete executor",
        "# (spec `specs/staged-delete.md` CP8). Use with iac/aws/.",
        'project    = "dt"',
        'region     = "us-west-2"',
        's3_buckets = ["alpha", "beta"]',
        "",
    ]


def test_cli_r2_bindings_matches_the_generator(tmp_path):
    p = tmp_path / "buckets.yml"
    p.write_text("buckets:\n  - r2://ctbk\n  - s3://sb\n")
    from disk_tree.cli.sync import load_config

    res = CliRunner().invoke(cli, ["iac", "r2-bindings", "-c", str(p)])
    assert res.exit_code == 0
    assert res.output == r2_bindings_toml(load_config(str(p)))
