// GENERATED by cloud/scripts/gen-identities-ts from identities.yaml — do not edit.
// Display-only enrichment (short name + GitHub avatar handle) keyed by
// canonical user id. Attribution (bytes) still comes from meta/rules.
export interface IdentityRec {
  u: string  // canonical user id (alias keys point at their canonical rec)
  name: string
  github?: string
}

export const IDENTITIES: Record<string, IdentityRec> = {
  "ahmed": {
    "github": "ahmeda14960",
    "name": "Ahmed",
    "u": "ahmed-ahmed"
  },
  "ahmed-ahmed": {
    "github": "ahmeda14960",
    "name": "Ahmed",
    "u": "ahmed-ahmed"
  },
  "ahmedah": {
    "github": "ahmeda14960",
    "name": "Ahmed",
    "u": "ahmed-ahmed"
  },
  "ahmedsqred": {
    "github": "ahmeda14960",
    "name": "Ahmed",
    "u": "ahmed-ahmed"
  },
  "alex-merose": {
    "github": "alxmrs",
    "name": "Alex",
    "u": "alex-merose"
  },
  "alxmrs": {
    "github": "alxmrs",
    "name": "Alex",
    "u": "alex-merose"
  },
  "babychousr": {
    "github": "BabyChouSr",
    "name": "Christopher",
    "u": "christopher-chou"
  },
  "benjamin-feuer": {
    "name": "Ben",
    "u": "benjamin-feuer"
  },
  "benjaminfeuer": {
    "name": "Ben",
    "u": "benjamin-feuer"
  },
  "blahblahhhj": {
    "github": "blahBlahhhJ",
    "name": "Jason",
    "u": "jason-wang"
  },
  "calvin-xu": {
    "github": "Calvin-Xu",
    "name": "Calvin",
    "u": "calvin-xu"
  },
  "calvinxu": {
    "github": "Calvin-Xu",
    "name": "Calvin",
    "u": "calvin-xu"
  },
  "calvinxu806": {
    "github": "Calvin-Xu",
    "name": "Calvin",
    "u": "calvin-xu"
  },
  "chi-heem-wong": {
    "github": "chiheem",
    "name": "Chi-Heem",
    "u": "chi-heem-wong"
  },
  "chiheem": {
    "github": "chiheem",
    "name": "Chi-Heem",
    "u": "chi-heem-wong"
  },
  "christopher-chou": {
    "github": "BabyChouSr",
    "name": "Christopher",
    "u": "christopher-chou"
  },
  "david-hall": {
    "github": "dlwh",
    "name": "David",
    "u": "david-hall"
  },
  "dlwh": {
    "github": "dlwh",
    "name": "David",
    "u": "david-hall"
  },
  "eczech": {
    "github": "eczech",
    "name": "Eric",
    "u": "eric-czech"
  },
  "elyas-obbad": {
    "github": "eobbad",
    "name": "Elyas",
    "u": "elyas-obbad"
  },
  "eobbad": {
    "github": "eobbad",
    "name": "Elyas",
    "u": "elyas-obbad"
  },
  "eric-czech": {
    "github": "eczech",
    "name": "Eric",
    "u": "eric-czech"
  },
  "exedev": {
    "name": "Exedev",
    "u": "exedev"
  },
  "gonzalo": {
    "github": "gonzalobenegas",
    "name": "Gonzalo",
    "u": "gonzalo-benegas"
  },
  "gonzalo-benegas": {
    "github": "gonzalobenegas",
    "name": "Gonzalo",
    "u": "gonzalo-benegas"
  },
  "gonzalobenegas": {
    "github": "gonzalobenegas",
    "name": "Gonzalo",
    "u": "gonzalo-benegas"
  },
  "held": {
    "github": "Helw150",
    "name": "Will",
    "u": "will-held"
  },
  "herumb-shandilya": {
    "github": "krypticmouse",
    "name": "Herumb",
    "u": "herumb-shandilya"
  },
  "herumb-stanford": {
    "github": "krypticmouse",
    "name": "Herumb",
    "u": "herumb-shandilya"
  },
  "jason-wang": {
    "github": "blahBlahhhJ",
    "name": "Jason",
    "u": "jason-wang"
  },
  "julian": {
    "github": "julian-q",
    "name": "Julian",
    "u": "julian"
  },
  "julian-q": {
    "github": "julian-q",
    "name": "Julian",
    "u": "julian"
  },
  "julianq": {
    "github": "julian-q",
    "name": "Julian",
    "u": "julian"
  },
  "kaiyue": {
    "github": "WhenWen",
    "name": "Kaiyue",
    "u": "kaiyue-wen"
  },
  "kaiyue-wen": {
    "github": "WhenWen",
    "name": "Kaiyue",
    "u": "kaiyue-wen"
  },
  "kaiyuew": {
    "github": "WhenWen",
    "name": "Kaiyue",
    "u": "kaiyue-wen"
  },
  "kaiyuewen3": {
    "github": "WhenWen",
    "name": "Kaiyue",
    "u": "kaiyue-wen"
  },
  "kevin-li": {
    "github": "AlienKevin",
    "name": "Kevin",
    "u": "kevin-li"
  },
  "kevinxli": {
    "github": "AlienKevin",
    "name": "Kevin",
    "u": "kevin-li"
  },
  "kothasuhas": {
    "github": "kothasuhas",
    "name": "Suhas",
    "u": "suhas-kotha"
  },
  "larry": {
    "github": "ClassicLarry",
    "name": "Larry",
    "u": "larry-dial"
  },
  "larry-dial": {
    "github": "ClassicLarry",
    "name": "Larry",
    "u": "larry-dial"
  },
  "larrydial": {
    "github": "ClassicLarry",
    "name": "Larry",
    "u": "larry-dial"
  },
  "matt-wittmann": {
    "github": "mcwitt",
    "name": "Matt",
    "u": "matt-wittmann"
  },
  "mcwitt": {
    "github": "mcwitt",
    "name": "Matt",
    "u": "matt-wittmann"
  },
  "michael-ryan": {
    "github": "XenonMolecule",
    "name": "Michael",
    "u": "michael-ryan"
  },
  "michaeljryan": {
    "github": "XenonMolecule",
    "name": "Michael",
    "u": "michael-ryan"
  },
  "michaelryan": {
    "github": "XenonMolecule",
    "name": "Michael",
    "u": "michael-ryan"
  },
  "moojin-kim": {
    "github": "moojink",
    "name": "Moojin",
    "u": "moojin-kim"
  },
  "moojink": {
    "github": "moojink",
    "name": "Moojin",
    "u": "moojin-kim"
  },
  "mryan0": {
    "github": "XenonMolecule",
    "name": "Michael",
    "u": "michael-ryan"
  },
  "nikil-ravi": {
    "github": "nikil-ravi",
    "name": "Nikil",
    "u": "nikil-ravi"
  },
  "percy-liang": {
    "github": "percyliang",
    "name": "Percy",
    "u": "percy-liang"
  },
  "percyliang": {
    "github": "percyliang",
    "name": "Percy",
    "u": "percy-liang"
  },
  "pinlinxu": {
    "github": "Calvin-Xu",
    "name": "Calvin",
    "u": "calvin-xu"
  },
  "power": {
    "github": "rjpower",
    "name": "Russell",
    "u": "russell-power"
  },
  "pranshu-01-c": {
    "github": "pc0618",
    "name": "Pranshu",
    "u": "pranshu-chaturvedi"
  },
  "pranshu-chaturvedi": {
    "github": "pc0618",
    "name": "Pranshu",
    "u": "pranshu-chaturvedi"
  },
  "rafal-wojdyla": {
    "github": "ravwojdyla",
    "name": "Rafal",
    "u": "rafal-wojdyla"
  },
  "rav": {
    "github": "ravwojdyla",
    "name": "Rafal",
    "u": "rafal-wojdyla"
  },
  "ravwojdyla": {
    "github": "ravwojdyla",
    "name": "Rafal",
    "u": "rafal-wojdyla"
  },
  "rohith-kuditipudi": {
    "github": "RohithKuditipudi",
    "name": "Rohith",
    "u": "rohith-kuditipudi"
  },
  "rohithk": {
    "github": "RohithKuditipudi",
    "name": "Rohith",
    "u": "rohith-kuditipudi"
  },
  "romain-yon": {
    "github": "yonromai",
    "name": "Romain",
    "u": "romain-yon"
  },
  "rpower": {
    "github": "rjpower",
    "name": "Russell",
    "u": "russell-power"
  },
  "runner": {
    "name": "Runner",
    "u": "runner"
  },
  "russell": {
    "github": "rjpower",
    "name": "Russell",
    "u": "russell-power"
  },
  "russell-power": {
    "github": "rjpower",
    "name": "Russell",
    "u": "russell-power"
  },
  "rw": {
    "github": "ryan-williams",
    "name": "Ryan",
    "u": "ryan-williams"
  },
  "ryan": {
    "github": "ryan-williams",
    "name": "Ryan",
    "u": "ryan-williams"
  },
  "ryan-williams": {
    "github": "ryan-williams",
    "name": "Ryan",
    "u": "ryan-williams"
  },
  "suhas-kotha": {
    "github": "kothasuhas",
    "name": "Suhas",
    "u": "suhas-kotha"
  },
  "teetone": {
    "github": "teetone",
    "name": "Tony",
    "u": "tony-lee"
  },
  "tony": {
    "github": "teetone",
    "name": "Tony",
    "u": "tony-lee"
  },
  "tony-lee": {
    "github": "teetone",
    "name": "Tony",
    "u": "tony-lee"
  },
  "when": {
    "github": "WhenWen",
    "name": "Kaiyue",
    "u": "kaiyue-wen"
  },
  "will-held": {
    "github": "Helw150",
    "name": "Will",
    "u": "will-held"
  },
  "yael-elmatad": {
    "github": "yaelelmatad",
    "name": "Yael",
    "u": "yael-elmatad"
  },
  "ziqing-huang": {
    "github": "ziqing-huang",
    "name": "Ziqing",
    "u": "ziqing-huang"
  },
  "ziqingh": {
    "github": "ziqing-huang",
    "name": "Ziqing",
    "u": "ziqing-huang"
  }
}
