// Object stores the dashboard can render. Each one publishes the same layer-3
// pair (`<base>/scans.json`, `<base>/<scan>/{age,meta}.json`) and lives at
// its own URL path, so adding a store is a row here plus data in the bucket.
//
// Data comes from the snapshot bucket via `functions/data/[[path]].ts`, not
// from the site build: GCS snapshots sit at `snapshots/<date>/`, and every
// other store would get a named subdir (`snapshots/<store>/<date>/`). The Function's
// date-dir filter keeps a store subdir out of the GCS scan list, and its
// generic `/data/<rel>` -> `snapshots/<rel>` mapping serves the payloads
// unchanged -- only the `scans.json` listing needed a store prefix.
//
// Baking the JSONs into `public/` was the other option; it was rejected because
// publishing a scan would then require a site redeploy, which is exactly the
// staleness the data Function was introduced to fix.
import type { ReactNode } from 'react'
import type { RuleShape } from './lifecycle'

/** The lifecycle fold's per-store shape (`LifecycleFold.tsx`). */
export interface LifecycleConfig {
  /** The tracked intended-state path the fold's note points at (`dt-cloud lifecycle diff|push`). */
  tracked: string
  /** The rule shape the scan job snapshots — picks the `lifecycle.ts` adapter:
   *  `s3` rules carry an `ID`, `gcs` rules are anonymous `{action, condition}`. */
  rules: RuleShape
  /** Fold rows a rule holds for across buckets into one (`groupRows`) — a
   *  fleet whose buckets share their rules shows each rule once with a
   *  buckets column. Off = one row per bucket, a bucket column grouping them. */
  grouped?: boolean
  /** The first scan with a snapshot; earlier scans skip the fetch (they'd only 404). */
  recordedFrom?: string
}

export interface Store {
  key: string
  label: string    // store selector button
  title: string    // <h1>, <title>, unfurl title
  desc: string     // meta description / unfurl description
  path: string     // app route
  scheme: string   // URI scheme for treemap paths/tooltips
  base: string     // layer-3 data root
  ogImage: string  // unfurl card, generated by `pnpm shots` from `<path>/og`
  prices: boolean  // GCS storage-class list pricing applies to this store
  /** The opt-in trash model: any full viewer proposes deletions by staging
   *  prefixes into a shared open plan (`POST /api/plans/stage`, the children
   *  table's trash gesture); an admin approves and dispatches from `/staged`.
   *  Off = the table has no delete gesture. Mirrors the Functions' `STAGING`
   *  var (the `stage_batches` table exists there). */
  staging: boolean
  /** The path filter's default syntax (`functions/_lib/querySyntax.ts` ids;
   *  `?qs=` overrides). Mirrors the Functions' `QUERY_SYNTAX`. Unset = `simple`. */
  querySyntax?: string
  /** Attribution + ownership: the owner axes (`?o=`), claims / assignments
   *  (admins assign; `POST /api/actions`), the `/users`, `/user/:id`,
   *  `/assignments` pages and the email → user map. Only the actions-ledger
   *  store has these. */
  owners: boolean
  /** Which executor route family `/staged` dispatches to: cw's plan-first
   *  Batch bridge (`/api/plan-sweep/*`, one bucket per run, undo + purge) or
   *  gcs's sweep bridge (`/api/sweep/*`, a plan may span buckets). */
  executor: 'plan-sweep' | 'sweep'
  /** Set when the scan job snapshots the buckets' lifecycle rules
   *  (`<base>/<scan>/lifecycle.json`): the home-page fold, and how this
   *  store's snapshots read. Unset = no fold. */
  lifecycle?: LifecycleConfig
  /** The buckets the scan covers, the first the primary (the quota / sweep
   *  default; what a bare `lifecycle.json` `Rules[]` from before the
   *  multi-bucket scan belongs to). */
  buckets: string[]
  /** The sibling deployment the site menu links to (each store is its own host). */
  peer?: { label: string; href: string }
  /** The login wall's copy — who may sign in here and how. Each deployment's
   *  own: gcs.oa.dev admits allow-listed non-OA accounts, PINs and share links;
   *  cw-s3.oa.dev is OA + CoreWeave staff. */
  wall: { restrict: string; signIn: string; how?: string }
  /** How the store's root reads in copy: the scope word for "all of it"
   *  (`all buckets` for the six-bucket fleet, `the whole bucket` for one). */
  rootLabel: string
  /** One sentence on what the listing's time means for this store's objects
   *  (the age chart's subtitle; the read axis adds its own clause when present). */
  objectsNote: string
  /** Buckets whose objects are publicly readable, by bucket: the base URL an
   *  opened object is range-read from (`<base>/<key>`, in the browser — so the
   *  bucket's CORS must admit this site). A bucket not here opens through the
   *  deployment's `/v1/files` proxy when that reads it, else shows size and
   *  dates only (`objects.ts` `objectSource`). */
  objectBases?: Record<string, string>
  /** Where viewers take ownership questions (`AttributionRules`): an email
   *  address and/or a chat link. Unset = no contact line. */
  contact?: { email?: string; chat?: { label: string; href: string } }
  /** The About panel's "The data" section, when the store says more than its
   *  `desc` (a deployment's pipeline, its data's history). Unset = `desc`. */
  about?: ReactNode
}

/** The registry: one module per store under `stores/` (each `export default`s a
 * `Store`), plus the inline entries below; a module wins over an inline entry
 * with its key. A deployment branch adds its store as a module, so the shared
 * base carries no deployment's entry (specs/oa-decoupling.md step 6). */
const MODULES = Object.values(import.meta.glob<{ default: Store }>('./stores/*.{ts,tsx}', { eager: true })).map(m => m.default)

const INLINE: Store[] = [
  {
    key: 'cw',
    label: 'CoreWeave',
    title: 'Marin CoreWeave usage',
    desc: 'Storage usage of the Marin CoreWeave buckets — treemap, diffs over time, and reviewed deletions.',
    path: '/',
    scheme: 's3://',
    base: '/data/cw',
    ogImage: '/og.jpg',
    prices: false,
    staging: false,
    owners: false,
    executor: 'plan-sweep',
    lifecycle: { tracked: 'job/cw-lifecycle.json', rules: 's3', recordedFrom: '2026-09-17' },
    buckets: ['marin-us-east-02a', 'hero-checkpoints'],
    peer: { label: 'GCS usage', href: 'https://gcs.oa.dev/' },
    rootLabel: 'all buckets',
    objectsNote: 'CoreWeave objects are written once by the training jobs and never rewritten in place, so created is the object’s only time.',
    wall: {
      restrict: 'Access is limited to Open Athena and CoreWeave staff.',
      signIn: 'Sign in with Open Athena',
      how: 'Use Google with your Open Athena or CoreWeave account, or have a one-time code emailed to it (no Google account needed). Invited guests can also use a personal share link.',
    },
  },
  {
    key: 'gcs',
    label: 'GCS',
    title: 'Marin GCS usage',
    desc: 'Per-user storage ownership across the six marin-* GCS buckets.',
    path: '/',
    scheme: 'gs://',
    base: '/data',
    ogImage: '/og.jpg',
    prices: true,
    staging: true,
    owners: true,
    executor: 'sweep',
    lifecycle: { tracked: 'job/lifecycle/', rules: 'gcs', grouped: true, recordedFrom: '2026-09-16' },
    buckets: ['marin-us-central2', 'marin-us-central1', 'marin-us-east1', 'marin-us-east5', 'marin-us-west4', 'marin-eu-west4'],
    peer: { label: 'CoreWeave usage', href: 'https://cw-s3.oa.dev/' },
    rootLabel: 'all buckets',
    objectsNote: 'GCS objects are written by the training jobs and rarely rewritten in place, so created is the object’s upload time; the read axis adds when it was last read.',
    wall: {
      restrict: 'Access is limited to marin contributors and invited collaborators.',
      signIn: 'Sign in',
      how: 'Use Google with any allow-listed account (Stanford, personal, or Open Athena), or have a one-time code emailed to any allow-listed address (no Google account needed). Invited guests can also use a personal share link.',
    },
  },
  {
    // The deploy's own storage (specs/multi-store.md): the scan + index data
    // the deployments write — the GCS snapshot bucket and its R2 mirror — as
    // a secondary store, mounted under `/meta` beside a primary (`STORES_EXTRA`).
    // Its data is the same layer-3 shape under `snapshots/meta/`, served by the
    // Functions with `store=meta` (`STORES_JSON` → `SNAPSHOTS_SUBDIR = meta`).
    // Staff-only server-side (the store's `scope`); no ownership ledger, no
    // trash gesture, no storage-class prices.
    key: 'meta',
    label: 'Meta',
    title: 'Our storage — scan & index data',
    desc: 'The scan and index data these deployments write (the GCS snapshot bucket and its R2 mirror) — treemap, sizes over time, and diffs.',
    path: '/meta',
    scheme: 'gs://',
    base: '/data/meta',
    ogImage: '/og.jpg',
    prices: false,
    staging: false,
    owners: false,
    executor: 'plan-sweep',
    buckets: ['oa-gcs-usage-dvx', 'oa-cw-s3-usage-index'],
    rootLabel: 'our storage',
    objectsNote: 'Scan outputs are written once per job run and never rewritten in place, so created is the object’s publish time.',
    wall: {
      restrict: 'The meta store is limited to Open Athena staff.',
      signIn: 'Sign in with Open Athena',
    },
  },
]

// A module takes its inline entry's place, so overriding an entry never
// reorders the registry (its first store is the unconfigured build's primary).
const REGISTRY: Store[] = [
  ...INLINE.map(s => MODULES.find(m => m.key === s.key) ?? s),
  ...MODULES.filter(m => !INLINE.some(s => s.key === m.key)),
]

/** The registry rows a build serves, primary first.
 *
 * A deployment serves one **primary** store, selected by `VITE_STORE` at build
 * time (unset = the first registry store, so the cw-s3 build is unchanged) —
 * the "deployment as configuration" seam for the shared base
 * (specs/union-of-roots.md). `VITE_STORES_EXTRA` (comma-separated keys) adds
 * **secondary** stores, each mounted under its own `path` (`/meta`) and read
 * through the same Functions with `store=<key>` (specs/multi-store.md phase 2).
 * The primary keeps `/` and its requests carry no `store=` at all, so a build
 * without extras is exactly the single-store build. A misconfiguration is a
 * build-time error, not an empty page. */
export function resolveStores(primary: string | undefined, extra: string | undefined): Store[] {
  const find = (key: string): Store => {
    const s = REGISTRY.find(r => r.key === key)
    if (!s) throw new Error(`stores: no registry store '${key}' (have ${REGISTRY.map(r => r.key).sort().join(', ')})`)
    return s
  }
  const first = primary ? find(primary) : REGISTRY[0]
  const out = [first]
  for (const key of [...new Set((extra ?? '').split(',').map(k => k.trim()).filter(Boolean))]) {
    if (key === first.key) throw new Error(`stores: '${key}' is the primary store (VITE_STORE); it can't also be in VITE_STORES_EXTRA`)
    const s = find(key)
    if (s.path === '/') throw new Error(`stores: secondary store '${key}' has no path of its own (path '/' is the primary's)`)
    if (out.some(o => o.path === s.path)) throw new Error(`stores: '${key}' shares path '${s.path}' with another configured store`)
    out.push(s)
  }
  return out
}

export const STORES: Store[] = resolveStores(import.meta.env.VITE_STORE, import.meta.env.VITE_STORES_EXTRA)

/** The primary store: `/`, and every request as it was before stores existed. */
export const DEFAULT_STORE = STORES[0]

/** The `store=<key>` a secondary store's requests carry; `''` for the primary
 * (`_lib/stores.ts` `requestedStore`: no param = the primary). */
export const storeQuery = (store: Store, primary: Store = DEFAULT_STORE): string =>
  store.key === primary.key ? '' : `store=${encodeURIComponent(store.key)}`

/** `url` as `store` fetches it: unchanged for the primary, else with
 * `store=<key>` appended to the query (`?` or `&` as needed). Every data
 * request (`/api/*`, `/data/*`, `/v1/files/*`) goes through this, so the
 * Functions resolve the store from the one param. */
export function storeUrl(url: string, store: Store, primary: Store = DEFAULT_STORE): string {
  const q = storeQuery(store, primary)
  if (!q) return url
  const hash = url.indexOf('#')
  const [head, frag] = hash < 0 ? [url, ''] : [url.slice(0, hash), url.slice(hash)]
  return `${head}${head.includes('?') ? '&' : '?'}${q}${frag}`
}

/** A `fetch` bound to `store`: the global one for the primary (byte-identical
 * requests), else one that rewrites each URL with `storeUrl`. Also what a
 * file-tree `HttpStore` takes as its `fetch` option. */
export function storeFetch(store: Store, primary: Store = DEFAULT_STORE, impl: typeof fetch = fetch): typeof fetch {
  if (!storeQuery(store, primary)) return impl
  return (input, init) => impl(
    typeof input === 'string' ? storeUrl(input, store, primary)
      : input instanceof URL ? storeUrl(input.toString(), store, primary)
      : new Request(storeUrl(input.url, store, primary), input),
    init,
  )
}

/** The configured store a location belongs to: the longest matching secondary
 * `path` (`/meta`, `/meta/…`), else the primary. */
export const storeForPath = (pathname: string, stores: Store[] = STORES): Store =>
  [...stores.slice(1)]
    .sort((a, b) => b.path.length - a.path.length)
    .find(s => pathname === s.path || pathname.startsWith(`${s.path}/`))
  ?? stores[0]
