// Object stores the dashboard can render. Each one publishes the same layer-3
// pair (`<base>/scans.json`, `<base>/<scan>/{age,meta}.json`) and lives at
// its own URL path, so adding a store is a row here plus data in the bucket.
//
// Data comes from the snapshot bucket via `functions/data/[[path]].ts`, not
// from the site build: GCS snapshots sit at `snapshots/<date>/`, and every
// other store would get a named subdir (`snapshots/<store>/<date>/`). The Function's
// date-dir filter keeps a store subdir out of the GCS scan list, and its
// generic `/data/<rel>` -> `snapshots/<rel>` mapping serves the payloads
// unchanged -- only the `scans.json` listing needed a store prefix.
//
// Baking the JSONs into `public/` was the other option; it was rejected because
// publishing a scan would then require a site redeploy, which is exactly the
// staleness the data Function was introduced to fix.
import type { RuleShape } from './lifecycle'

/** The lifecycle fold's per-store shape (`LifecycleFold.tsx`). */
export interface LifecycleConfig {
  /** The tracked intended-state path the fold's note points at (`dt-cloud lifecycle diff|push`). */
  tracked: string
  /** The rule shape the scan job snapshots — picks the `lifecycle.ts` adapter:
   *  `s3` rules carry an `ID`, `gcs` rules are anonymous `{action, condition}`. */
  rules: RuleShape
  /** Fold rows a rule holds for across buckets into one (`groupRows`) — a
   *  fleet whose buckets share their rules shows each rule once with a
   *  buckets column. Off = one row per bucket, a bucket column grouping them. */
  grouped?: boolean
  /** The first scan with a snapshot; earlier scans skip the fetch (they'd only 404). */
  recordedFrom?: string
}

export interface Store {
  key: string
  label: string    // store selector button
  title: string    // <h1>, <title>, unfurl title
  desc: string     // meta description / unfurl description
  path: string     // app route
  scheme: string   // URI scheme for treemap paths/tooltips
  base: string     // layer-3 data root
  ogImage: string  // unfurl card, generated by `pnpm shots` from `<path>/og`
  prices: boolean  // GCS storage-class list pricing applies to this store
  /** The opt-in trash model: any full viewer proposes deletions by staging
   *  prefixes into a shared open plan (`POST /api/plans/stage`, the children
   *  table's trash gesture); an admin approves and dispatches from `/staged`.
   *  Off = the table has no delete gesture. Mirrors the Functions' `STAGING`
   *  var (the `stage_batches` table exists there). */
  staging: boolean
  /** Attribution + ownership: the owner axes (`?o=`), claims / assignments
   *  (admins assign; `POST /api/actions`), the `/users`, `/user/:id`,
   *  `/assignments` pages and the email → user map. Only the actions-ledger
   *  store has these. */
  owners: boolean
  /** Which executor route family `/staged` dispatches to: cw's plan-first
   *  Batch bridge (`/api/plan-sweep/*`, one bucket per run, undo + purge) or
   *  gcs's sweep bridge (`/api/sweep/*`, a plan may span buckets). */
  executor: 'plan-sweep' | 'sweep' | 'laptop'
  /** Set when the scan job snapshots the buckets' lifecycle rules
   *  (`<base>/<scan>/lifecycle.json`): the home-page fold, and how this
   *  store's snapshots read. Unset = no fold. */
  lifecycle?: LifecycleConfig
  /** The buckets the scan covers, the first the primary (the quota / sweep
   *  default; what a bare `lifecycle.json` `Rules[]` from before the
   *  multi-bucket scan belongs to). */
  buckets: string[]
  /** The sibling deployment the site menu links to (each store is its own host). */
  peer?: { label: string; href: string }
  /** The login wall's copy — who may sign in here and how. Each deployment's
   *  own: gcs.oa.dev admits allow-listed non-OA accounts, PINs and share links;
   *  cw-s3.oa.dev is OA + CoreWeave staff. */
  wall: { restrict: string; signIn: string; how?: string }
  /** How the store's root reads in copy: the scope word for "all of it"
   *  (`all buckets` for the six-bucket fleet, `the whole bucket` for one). */
  rootLabel: string
  /** One sentence on what the listing's time means for this store's objects
   *  (the age chart's subtitle; the read axis adds its own clause when present). */
  objectsNote: string
}

const REGISTRY: Store[] = [
  {
    key: 'cw',
    label: 'CoreWeave',
    title: 'Marin CoreWeave usage',
    desc: 'Storage usage of the Marin CoreWeave buckets — treemap, diffs over time, and reviewed deletions.',
    path: '/',
    scheme: 's3://',
    base: '/data/cw',
    ogImage: '/og.jpg',
    prices: false,
    staging: false,
    owners: false,
    executor: 'plan-sweep',
    lifecycle: { tracked: 'job/cw-lifecycle.json', rules: 's3', recordedFrom: '2026-09-17' },
    buckets: ['marin-us-east-02a', 'hero-checkpoints'],
    peer: { label: 'GCS usage', href: 'https://gcs.oa.dev/' },
    rootLabel: 'all buckets',
    objectsNote: 'CoreWeave objects are written once by the training jobs and never rewritten in place, so created is the object’s only time.',
    wall: {
      restrict: 'Access is limited to Open Athena and CoreWeave staff.',
      signIn: 'Sign in with Open Athena',
      how: 'Use Google with your Open Athena or CoreWeave account, or have a one-time code emailed to it (no Google account needed). Invited guests can also use a personal share link.',
    },
  },
  {
    key: 'gcs',
    label: 'GCS',
    title: 'Marin GCS usage',
    desc: 'Per-user storage ownership across the six marin-* GCS buckets.',
    path: '/',
    scheme: 'gs://',
    base: '/data',
    ogImage: '/og.jpg',
    prices: true,
    staging: true,
    owners: true,
    executor: 'sweep',
    lifecycle: { tracked: 'job/lifecycle/', rules: 'gcs', grouped: true, recordedFrom: '2026-09-16' },
    buckets: ['marin-us-central2', 'marin-us-central1', 'marin-us-east1', 'marin-us-east5', 'marin-us-west4', 'marin-eu-west4'],
    peer: { label: 'CoreWeave usage', href: 'https://cw-s3.oa.dev/' },
    rootLabel: 'all buckets',
    objectsNote: 'GCS objects are written by the training jobs and rarely rewritten in place, so created is the object’s upload time; the read axis adds when it was last read.',
    wall: {
      restrict: 'Access is limited to marin contributors and invited collaborators.',
      signIn: 'Sign in',
      how: 'Use Google with any allow-listed account (Stanford, personal, or Open Athena), or have a one-time code emailed to any allow-listed address (no Google account needed). Invited guests can also use a personal share link.',
    },
  },
  {
    key: 'r2',
    label: 'R2',
    title: 'disk-tree — public R2 buckets',
    desc: 'Storage usage of public Cloudflare R2 buckets (ctbk, crashes, jc-taxes) — treemap, sizes over time, and diffs. A public disk-tree demo.',
    path: '/',
    scheme: 'r2://',
    base: '/data/r2',
    ogImage: '/og.jpg',
    prices: false,
    staging: false,
    owners: false,
    executor: 'plan-sweep',
    buckets: ['ctbk', 'crashes', 'jc-taxes'],
    rootLabel: 'all buckets',
    objectsNote: 'Public R2 buckets scanned daily by disk-tree; created is each object’s upload time.',
    // A public deploy never shows the wall (`AUTH_MODE === 'public'`); copy
    // kept for the type, and for a gated build of the same store.
    wall: { restrict: 'This store is public.', signIn: 'Sign in' },
  },
  {
    key: 'laptop',
    label: 'Laptop',
    title: 'disk-tree — m3',
    desc: 'Disk usage of one laptop, captured every 12 h — treemap, sizes over time, diffs, and staged deletes executed on the laptop.',
    path: '/',
    scheme: 'file:///',  // + the root sans leading slash (dt-cloud path-index strips it)
    base: '/data/laptop',
    ogImage: '/og.jpg',
    prices: false,
    staging: true,
    owners: false,
    // The laptop's own drainer executes runs (`_lib/laptopDispatch.ts`).
    executor: 'laptop',
    // Roots are scanned directories (`/Users/ryan`), not buckets.
    buckets: [],
    rootLabel: 'all roots',
    objectsNote: 'Local files; created is each file’s mtime at capture time.',
    wall: {
      restrict: 'This laptop’s disk usage is private to its owner.',
      signIn: 'Sign in',
    },
  },
]

// A deployment serves one store, selected by VITE_STORE at build time (unset =
// the first registry store, so the cw-s3 build is unchanged). The "deployment
// as configuration" seam for the shared base (specs/union-of-roots.md).
export const STORES: Store[] = import.meta.env.VITE_STORE
  ? REGISTRY.filter(s => s.key === import.meta.env.VITE_STORE)
  : [REGISTRY[0]]

export const DEFAULT_STORE = STORES[0]

// Longest matching path wins. (This deployment — cw-s3.oa.dev, the `cw-s3`
// branch — serves the CoreWeave store only; the GCS view is gcs.oa.dev.)
export const storeForPath = (pathname: string): Store =>
  [...STORES]
    .sort((a, b) => b.path.length - a.path.length)
    .find(s => s.path !== '/' && (pathname === s.path || pathname.startsWith(`${s.path}/`)))
  ?? DEFAULT_STORE
