"""Generate deployment config for the executor resources (spec
``specs/staged-delete.md``, CP8) from ``buckets.yml``.

The staged-delete executors need per-deployment wiring: the edge R2 CFN (CP7)
needs an ``R2_<bucket>`` binding per bucket it may delete; the Pulumi
``CfnDashboard`` component (``iac/``) needs the same set plus the delete policy.
Deriving both from the one ``buckets.yml`` keeps setup a single source of truth
rather than hand-maintained parallel config.

Pure functions here (config -> text/dict); the CLI (`cli/iac.py`) is the shell.
"""
from __future__ import annotations

import re


def binding_name(host: str) -> str:
    """The wrangler R2 binding for a bucket: ``R2_<host>``, the host sanitized to
    a valid identifier (mirrors ``ui/cfn/r2exec.ts`` ``r2Binding``)."""
    return f"R2_{re.sub(r'[^A-Za-z0-9_]', '_', host)}"


def r2_hosts(cfg) -> list[str]:
    """The distinct R2 bucket hosts in a ``SyncCfg``, in config order."""
    seen: dict[str, None] = {}
    for b in cfg.buckets:
        if b.scheme == "r2":
            seen.setdefault(b.host, None)
    return list(seen)


def r2_bindings_toml(cfg) -> str:
    """The ``wrangler.toml`` ``[[r2_buckets]]`` blocks binding each configured R2
    bucket for the CFN executor (CP7). Empty (a comment) if there are none."""
    hosts = r2_hosts(cfg)
    if not hosts:
        return "# no r2:// buckets in buckets.yml — nothing to bind for the R2 CFN\n"
    lines = [
        "# Generated by `disk-tree iac r2-bindings` — R2 CFN executor bindings",
        "# (spec `specs/staged-delete.md` CP7). Paste into ui/wrangler.toml, redeploy.",
    ]
    for host in hosts:
        lines += ["", "[[r2_buckets]]", f'binding = "{binding_name(host)}"', f'bucket_name = "{host}"']
    return "\n".join(lines) + "\n"


def dashboard_config(cfg, *, project: str = "disk-tree", data_bucket: str = "disk-tree") -> dict:
    """The ``CfnDashboard`` Pulumi component's config (``iac/``): the CF reference
    deploy plus the CP7 executor bindings and the delete policy."""
    delete = cfg.delete or {}
    return {
        "project": project,
        "dataBucket": data_bucket,
        "deleteThreshold": int(delete.get("threshold", 1000)),
        "deleteApproval": delete.get("approval", "staged"),
        "chat": delete.get("chat", "none"),
        "executorBuckets": [{"binding": binding_name(h), "bucket": h} for h in r2_hosts(cfg)],
    }
